# contains pydantic classes
# enforces type-checking of incoming json packages and validates outcoming json payloads generated by director
from datetime import datetime
from typing import Dict, Any, Optional

from pydantic import BaseModel, PositiveInt
import uuid

class GameEvent(BaseModel):
    id: uuid.UUID
    label: str
    timestamp: datetime
    location: Optional[str] = "Not assigned."
    details: Optional[Dict[str, Any]] = None
