# contains pydantic classes
# enforces type-checking of incoming json packages and validates outcoming json payloads generated by director
import uuid
from pydantic import BaseModel, Field, AfterValidator
from typing import Any, Dict, Union, Optional, List


class GameEventModel(BaseModel):
    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        description="Unique identifier for the event. Automatically generated if not provided."
    )
    label: str = Field(
        ...,
        description="A concise, highly descriptive summary of the event that just occurred (e.g., 'Player received a strange radar signal from satellite dish Alpha.')."
    )
    timestamp: float = Field(
        ...,
        description="The time the event occurred, represented as a float (in-game seconds or Unix epoch). This drives the memory decay engine."
    )
    location: Optional[str] = Field(
        default="Not assigned.",
        description="The specific in-game location or room where the event took place."
    )
    importance: float = Field(
        default=1.0,
        ge=0.1,
        le=10.0,
        description="Importance score of the event from 0.1 (trivial/background noise) to 10.0 (critical anomaly, alien encounter, or major plot point)."
    )
    details: Optional[Dict[str, Union[str, int, float, bool]]] = Field(
        default=None,
        description="Extra contextual key-value pairs (e.g., {'entity_spotted': true, 'signal_strength': 85.5}). Values MUST be strings, integers, floats, or booleans only. No nested objects."
    )


class EventExtractionModel(BaseModel):
    extracted_events: List[GameEventModel] = Field(
        description="A list of semantically chunked and filtered events extracted from the raw telemetry. Outputted by miner."
    )


def is_clamped(value: int) ->int:
    if -300<value<300:
        return value
    else:
        raise ValueError("Delta value must be between -300 and 300.")

class ProfileJSONModel(BaseModel):
    deltas: Dict[str, Any]

# an event that would be sent to game from director,
# contains an action and a payload (which can be used to trigger specific in-game mechanics,
# spawn entities, or alter the game state in a way that aligns with the narrative direction)
class DirectorEventModel(BaseModel):
    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        description="Unique identifier for the event. Automatically generated if not provided."

    )
    type: str = Field(
        description="Type of event sent."
    )
    data: Dict[str, Any] = Field(
        description="The payload. Depends on the type of the event."
    )