# contains pydantic classes
# enforces type-checking of incoming json packages and validates outcoming json payloads generated by director
from datetime import datetime
from typing import Dict, Any, Optional
from pydantic import BaseModel
import uuid

class GameEventModel(BaseModel):
    id: uuid.UUID
    label: str
    timestamp: datetime
    location: Optional[str] = "Not assigned."
    importance: Optional[float] = 1
    details: Optional[Dict[str, Any]] = None
